### ISSUE TITLE
Unrecognized Selector sent to instance 0x12566b30

### ISSUE THREAD

**Issue by confile** [inFullMobile/WobbleView#3]
I tested the Example on Target 7.0 iPhone5 and got the following error: 

```
terminating with uncaught exception of type NSException
```

![appdelegate_swift](https://cloud.githubusercontent.com/assets/64265/7164091/48435110-e39e-11e4-9a0f-6f27385e7a5a.png)

**Comment by atomhax** [comment]
confile,

I hate to be 'that guy' but I downloaded the example project. Changed my deployment target to 7.0 and launched the example project on the iphone 5 simulator. It launched without issue. I'm on Xcode version 6.3 (6D570). 

The real error is not "terminating with uncaught exception of type NSException" it's  above that. "Unrecognized Selector sent to instance 0x12566b30". Usually this error means you are calling a method on an object which is released or has not been initialized yet. Did you make any changes to the code?

Maybe try updating xcode if you have not already done so. If you upload your version of the example code I can double check it. 

I'm not associated with the project. I just was interested in checking the issue page. I don't speak for the authors in any way, shape or form. 

-atomhax

**Comment by kondratk** [comment]
@confile @atomhax 
Actually the app crashes on iOS7 because of lack of layoutMargins and preservesSuperviewLayoutMargins properties in UIView class which were introduced in iOS8 SDK.

The WobbleView itself does not cause the crash- it happens because of using the newest api in example UITableViewCell. 

According to iOS 8 Release Notes:
"The leftLayoutGuide and rightLayoutGuide APIs have been removed. Please use the layoutMargins property instead."

https://developer.apple.com/library/prerelease/ios/releasenotes/General/RN-iOSSDK-8.0/

Regards,
Kondrat

**Comment by drmichaelgorski** [comment]
@atomhax I did not change anything in the code.

**Comment by drmichaelgorski** [comment]
@kondratk Thus this means that it does not work with iOS7?

**Comment by kondratk** [comment]
@confile The WobbleView **does**, but the example doesn't :)

**Comment by drmichaelgorski** [comment]
Well why not?

**Comment by kondratk** [comment]
@confile Read my first post- that's why!

**Comment by kondratk** [comment]
@confile Issues should be fixed in latest pull request #7 
Try it ;)

**Comment by wojteklu** [comment]
@kondratk Good job. Thanks! :)

**Comment by drmichaelgorski** [comment]
Thanks now its working!
